---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: create voctomix directories
  become: true
  file: dest={{ item }} state=directory
        owner=root group=root
  with_items:
    - /opt/voc/scripts/
    - /opt/voc/release/

  # alternative gui
- name: install alternative gui for 4 sources on a amall display (horizontal layout)
  become: true
  copy: src=voctomix-alternative-gui/
        dest=/opt/voc/voctomix-alternative-gui/
        directory_mode=0755
        mode=0644 owner=root group=root
  when: alternative_gui_for_voctogui | bool


  # voctogui service
- name: create voctogui systemd-unit
  become: true
  template:
    src: systemd-units/voctomix-voctogui.service.j2
    dest: /etc/systemd/system/voctomix-voctogui.service
    mode: 0644
    owner: root
    group: root

- name: enable & start voctogui service when in voctomix-mode
  become: true
  systemd:
    name: voctomix-voctogui.service
    daemon_reload: yes
    enabled: yes
    state: started
  when: encodermode is defined and encodermode == 'hd-voctomix'

- name: disable & stop voctogui service when not in voctomix-mode
  become: true
  systemd: name=voctomix-voctogui
           enabled=no
           state=stopped
  when: encodermode is not defined or encodermode != 'hd-voctomix'

